#!/usr/bin/env bash
#
# ahc-root-input: validate
# Reads the requested window from maintenance-window.json and re-parses it here; a malformed
# time is refused, never coerced into something that would land in a root-run unit.
# Apply the household's chosen maintenance window to the apt-daily-upgrade timer.
#
# Takes NO arguments, deliberately. The sudoers policy for this service allows exact commands with
# no wildcards, so a helper that accepted a time on the command line would need a wildcard rule and
# would widen what the service user can ask root to do. Instead the backend writes its choice to a
# file inside its own data directory — which needs no privilege at all — and this reads it.
#
# That makes this script a privilege boundary, and the input untrusted even though the service
# wrote it: anything able to write that file could otherwise inject arbitrary lines into a systemd
# unit that runs as root. Hence the strict validation below, and a refusal rather than a default on
# anything unexpected.

set -euo pipefail

REQUEST=/var/lib/aihomecloud/maintenance-window.json
DROPIN_DIR=/etc/systemd/system/apt-daily-upgrade.timer.d
DROPIN="$DROPIN_DIR/50-ahc-window.conf"

[[ $EUID -eq 0 ]] || { echo "must run as root" >&2; exit 1; }
[[ -f "$REQUEST" ]] || { echo "no window requested at $REQUEST" >&2; exit 2; }

# Parse without a JSON library — python3 is present on every board, and this stays readable.
read -r START WINDOW_H TZ_REQ <<<"$(python3 - "$REQUEST" <<'PY'
import json, sys
try:
    d = json.load(open(sys.argv[1]))
except Exception:
    sys.exit(3)
print(str(d.get("start", "")), str(d.get("durationHours", "")), str(d.get("timezone", "")))
PY
)" || { echo "unreadable request file" >&2; exit 3; }

# HH:MM, 24-hour, nothing else. This is what stops a newline or a systemd directive reaching the
# unit file: a value that does not match is refused, never sanitised and used anyway.
[[ "$START" =~ ^([01][0-9]|2[0-3]):[0-5][0-9]$ ]] || { echo "invalid start time: '$START'" >&2; exit 4; }
[[ "$WINDOW_H" =~ ^[1-9]$|^1[0-2]$ ]] || { echo "invalid duration: '$WINDOW_H'" >&2; exit 5; }

# The timezone is applied here, from the same file, because it is the same question.
#
# "03:30" is meaningless without it, and the failure is silent: the production board shipped on
# Etc/UTC, so a household choosing half past three would have had its NAS updating and restarting at
# 09:00 their time — the busiest part of the morning, and precisely what the window exists to avoid.
# Validated against the system's own zone list rather than a regex, so nothing unexpected reaches
# timedatectl, and no separate sudoers entry is needed for it.
if [[ -n "${TZ_REQ:-}" && "$TZ_REQ" != "None" ]]; then
  if timedatectl list-timezones 2>/dev/null | grep -qxF "$TZ_REQ"; then
    timedatectl set-timezone "$TZ_REQ"
  else
    echo "unknown timezone: '$TZ_REQ'" >&2; exit 6
  fi
fi

# RandomizedDelaySec spreads the run across the window the household picked, so several boards on
# one network do not all wake and hammer the same mirror at exactly the same second.
DELAY=$(( WINDOW_H * 3600 ))

mkdir -p "$DROPIN_DIR"
cat > "$DROPIN" <<EOF
# Generated by ahc-apply-maintenance-window.sh — do not edit; the app owns this file.
# Household maintenance window: ${START} for ${WINDOW_H}h.
[Timer]
OnCalendar=
OnCalendar=*-*-* ${START}:00
RandomizedDelaySec=${DELAY}
Persistent=true
EOF

systemctl daemon-reload
systemctl restart apt-daily-upgrade.timer 2>/dev/null || true

NEXT=$(systemctl show apt-daily-upgrade.timer -p NextElapseUSecRealtime --value 2>/dev/null || true)
echo "applied ${START} +${WINDOW_H}h tz=$(timedatectl show -p Timezone --value) (next: ${NEXT:-unknown})"
